//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property can be changed only before the enumeration..
        /// </summary>
        internal static string InvalidResXBasePathOperation {
            get {
                return ResourceManager.GetString("InvalidResXBasePathOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResX file {0} cannot be parsed..
        /// </summary>
        internal static string InvalidResXFile {
            get {
                return ResourceManager.GetString("InvalidResXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResX input is not valid. Cannot find valid &quot;resheader&quot; tags for the ResX reader and writer type names..
        /// </summary>
        internal static string InvalidResXFileReaderWriterTypes {
            get {
                return ResourceManager.GetString("InvalidResXFileReaderWriterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a type for a name.  The type name was &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidResXNoType {
            get {
                return ResourceManager.GetString("InvalidResXNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a name for the resource with the value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidResXResourceNoName {
            get {
                return ResourceManager.GetString("InvalidResXResourceNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} in the data at line {1}, position {2}, cannot be loaded because it threw the following exception during construction: {3}.
        /// </summary>
        internal static string InvocationException {
            get {
                return ResourceManager.GetString("InvocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item named &apos;{0}&apos; of type &apos;{1}&apos; cannot be added to the resource file because it is not serializable..
        /// </summary>
        internal static string NotSerializableType {
            get {
                return ResourceManager.GetString("NotSerializableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} on line {1}, position {2} threw the following exception while being converted: {3}.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource writer has been saved.  You may not edit it..
        /// </summary>
        internal static string ResXResourceWriterSaved {
            get {
                return ResourceManager.GetString("ResXResourceWriterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} could not be read from the data in line {1}, position {2}.  The type&apos;s internal structure may have changed.  Either implement ISerializable on the type or provide a type converter that can provide a more reliable conversion format, such as text or an array of bytes.  The conversion exception was: {3}.
        /// </summary>
        internal static string SerializationException {
            get {
                return ResourceManager.GetString("SerializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} in the data at line {1}, position {2} cannot be located..
        /// </summary>
        internal static string TypeLoadException {
            get {
                return ResourceManager.GetString("TypeLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} cannot be located..
        /// </summary>
        internal static string TypeLoadExceptionShort {
            get {
                return ResourceManager.GetString("TypeLoadExceptionShort", resourceCulture);
            }
        }
    }
}
